### ISSUE TITLE
How to make changes in configuration file

### ISSUE THREAD

**Issue by skjainmiah** [AnikaTabassum/internship#2]
How to changes in configuration file? what you said I followed exactly  and now when I entered the command sudo nano /etc/nginx/conf.d/default.conf and it opened a terminal and now what should I type exactly I'm not getting. can you help me out with this? thank you. 

server_name  [your server ip];
root /data/myChatBotWeb;

**Comment by AnikaTabassum** [comment]
can you show me your /etc/nginx/conf.d/default.conf file?

**Comment by skjainmiah** [comment]
This is what I typed in the newly opened terminal and I didn't find any save or change button
![Screenshot at 2020-03-19 12-31-09](https://user-images.githubusercontent.com/17299453/77040245-8e0b1000-69dd-11ea-8161-ab70ee46014f.png)

**Comment by AnikaTabassum** [comment]
okay, the thing is your nginx configuration file is somewhere else. It could be /etc/nginx/nginx.conf
kindly find where is your nginx.conf file and make changes there. 
and to save a file using nano you have to press ctrl+x then y to confirm the saving. thanks!

**Comment by skjainmiah** [comment]
I'm using linux mint how to find where is my nginx configuration file any command for that?

**Comment by skjainmiah** [comment]
What I typed in the image is correct? and what should I change is path on the top of the terminal to /etc/nginx/nginx.conf is it correct?

**Comment by AnikaTabassum** [comment]
i worked with debian and redhat. so you better search for it somewhere else. Moreover the configuration file varies from version to version of nginx. it's safe to follow a renowned tutorial to install nginx on linux mint.

**Comment by skjainmiah** [comment]
One last question. Did you deployed your Rasa chatbot into a website? is it running currently?

**Comment by AnikaTabassum** [comment]
look, the default.conf file is not your nginx configuration file. so making any changes in it is not going to affect. One more thing, are you sure your nginx is running properly? kindly check it from a web browser. And yes I have deployed and it's currently running in a linux server

**Comment by skjainmiah** [comment]
Yes, it is showing running active

**Comment by AnikaTabassum** [comment]
can you give the command ls /etc/nginx and show me the output?

**Comment by skjainmiah** [comment]
This is what I got
![Screenshot at 2020-03-19 12-50-31](https://user-images.githubusercontent.com/17299453/77041621-40dc6d80-69e0-11ea-8296-5e67232e217a.png)

**Comment by AnikaTabassum** [comment]
I guess the nginx.conf file is your configuration file. open that with **sudo nano /etc/nginx/nginx.conf** and find where the path of root directory is.. replace the path of root directory with your bot web directory

**Comment by skjainmiah** [comment]
This is what I got and my path of root directory is root@test2:/home/test2#  and madam as I'm new to this linux I couldn't understand and I'm consuming your time. Sorry for it. But you helped a lot. Thanks for that.
![Screenshot at 2020-03-19 12-57-09](https://user-images.githubusercontent.com/17299453/77042140-2fe02c00-69e1-11ea-9678-c468bee75cd1.png)

**Comment by skjainmiah** [comment]
![Screenshot at 2020-03-19 13-03-01](https://user-images.githubusercontent.com/17299453/77042603-fbb93b00-69e1-11ea-8070-f682459fd421.png)

**Comment by AnikaTabassum** [comment]
I am sorry. I couldn't make you understand. 

> This is what I got and my path of root directory is root@test2:/home/test2# and madam as I'm new to this linux I couldn't understand and I'm consuming your time. Sorry for it. But you helped a lot. Thanks for that.
> ![Screenshot at 2020-03-19 12-57-09](https://user-images.githubusercontent.com/17299453/77042140-2fe02c00-69e1-11ea-9678-c468bee75cd1.png)

this is your configuration file... kindly find where **root** is mentioned in this file ans send a screenshot

**Comment by skjainmiah** [comment]
![Screenshot at 2020-03-19 13-21-18](https://user-images.githubusercontent.com/17299453/77043942-8bf87f80-69e4-11ea-89f9-c4c30faae57d.png)

**Comment by skjainmiah** [comment]
root@test2:~# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful



![Screenshot at 2020-03-19 13-26-57](https://user-images.githubusercontent.com/17299453/77044371-53a57100-69e5-11ea-8004-6757590337fe.png)

**Comment by AnikaTabassum** [comment]
there should be a line like this:
![Screenshot from 2020-03-19 13-57-38](https://user-images.githubusercontent.com/35559892/77044468-b436ad00-69e9-11ea-8274-3a43932c18f1.png)

**Comment by skjainmiah** [comment]
when I followed /etc/nginx/conf.d/default.conf   it is empty and there is no server like thing written there(actually your image contains server and other things written). and when I open /etc/nginx/nginx.conf there html template which I already sent to you. 

![Screenshot at 2020-03-19 13-37-01](https://user-images.githubusercontent.com/17299453/77045193-bba88700-69e6-11ea-86c9-36b942ffa8bf.png)

**Comment by skjainmiah** [comment]
![Screenshot at 2020-03-19 13-21-18](https://user-images.githubusercontent.com/17299453/77045436-32458480-69e7-11ea-8bfc-d8cbc51883ea.png)
![Screenshot at 2020-03-19 13-37-01](https://user-images.githubusercontent.com/17299453/77045439-34a7de80-69e7-11ea-8cfb-01985399ae5c.png)

**Comment by AnikaTabassum** [comment]
maybe I can't help you.. kindly search for **server** like thing in your /etc/nginx/nginx.conf file. As I said earlier, the configuration file varies from version to version.
